# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/guru/Work/CameraCalibration

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/guru/Work/CameraCalibration

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/guru/Work/CameraCalibration/CMakeFiles /home/guru/Work/CameraCalibration/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/guru/Work/CameraCalibration/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CameraCalibration

# Build rule for target.
CameraCalibration: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CameraCalibration
.PHONY : CameraCalibration

# fast build rule for target.
CameraCalibration/fast:
	$(MAKE) -f CMakeFiles/CameraCalibration.dir/build.make CMakeFiles/CameraCalibration.dir/build
.PHONY : CameraCalibration/fast

HelloWorld2.o: HelloWorld2.cpp.o
.PHONY : HelloWorld2.o

# target to build an object file
HelloWorld2.cpp.o:
	$(MAKE) -f CMakeFiles/CameraCalibration.dir/build.make CMakeFiles/CameraCalibration.dir/HelloWorld2.cpp.o
.PHONY : HelloWorld2.cpp.o

HelloWorld2.i: HelloWorld2.cpp.i
.PHONY : HelloWorld2.i

# target to preprocess a source file
HelloWorld2.cpp.i:
	$(MAKE) -f CMakeFiles/CameraCalibration.dir/build.make CMakeFiles/CameraCalibration.dir/HelloWorld2.cpp.i
.PHONY : HelloWorld2.cpp.i

HelloWorld2.s: HelloWorld2.cpp.s
.PHONY : HelloWorld2.s

# target to generate assembly for a file
HelloWorld2.cpp.s:
	$(MAKE) -f CMakeFiles/CameraCalibration.dir/build.make CMakeFiles/CameraCalibration.dir/HelloWorld2.cpp.s
.PHONY : HelloWorld2.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... CameraCalibration"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... HelloWorld2.o"
	@echo "... HelloWorld2.i"
	@echo "... HelloWorld2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

